apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ikasospa/gestiontaches-gitops.git'
    targetRevision: HEAD
    path: backend
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gestion-tache
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
