apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gestiontache-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ikasospa/gestiontaches-gitops.git'
    targetRevision: HEAD
    # Racine du dépôt
    path: '.'
    # INDISPENSABLE : scanne récursivement TOUS les sous-dossiers
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    # laisser vide ou utiliser "default" car les manifests
    # déclarent eux-mêmes leur namespace (gestion-tache, postgres, etc.)
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
